var page = require('webpage').create(),
  system = require('system'),
  url = system.args[1] || 'about:blank',
  objName = system.args[2] || 'window';

page.open(url, function (status) {
  var res = page.evaluate(function (ons) {
    var jqkeys = {
      '1.0': {
        "jQuery":"active/ajax/ajaxTimeout/attr/boxModel/browser/className/clean/css/curCSS/dequeue/each/event/expr/extend/filter/find/fn/fx/get/getAll/getIfModified/getScript/grep/httpData/httpNotModified/httpSuccess/init/initDone/isReady/lastModified/macros/map/merge/param/parents/parse/post/queue/ready/readyList/setAuto/sibling/speed/swap/timeout/token/trim",
        "jQuery.fn":"_hide/_show/_toggle/add/addClass/after/ajaxComplete/ajaxError/ajaxStart/ajaxStop/ajaxSuccess/ancestors/animate/append/appendTo/attr/background/before/bind/blur/change/children/click/clone/color/contains/css/dblclick/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/filter/find/float/focus/get/gt/height/hide/hover/href/html/id/index/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/left/load/loadIfModified/lt/mousedown/mousemove/mouseout/mouseover/mouseup/name/next/not/oneblur/onechange/oneclick/onedblclick/oneerror/onefocus/onekeydown/onekeypress/onekeyup/oneload/onemousedown/onemousemove/onemouseout/onemouseover/onemouseup/onereset/oneresize/onescroll/oneselect/onesubmit/oneunload/overflow/parent/parents/position/prepend/prependTo/prev/pushStack/queue/ready/rel/remove/removeAttr/removeClass/reset/resize/scroll/select/show/siblings/size/slideDown/slideToggle/slideUp/src/submit/text/title/toggle/toggleClass/top/trigger/unbind/unblur/unchange/unclick/undblclick/unerror/unfocus/unkeydown/unkeypress/unkeyup/unload/unmousedown/unmousemove/unmouseout/unmouseover/unmouseup/unreset/unresize/unscroll/unselect/unsubmit/ununload/val/width/wrap"
      },
      '1.1': {
        'jQuery':'active/ajax/ajaxSettings/ajaxSetup/ajaxTimeout/attr/boxModel/browser/className/clean/css/curCSS/dequeue/each/easing/event/expr/extend/filter/find/fn/fx/get/getAll/getIfModified/getJSON/getScript/globalEval/grep/handleError/httpData/httpNotModified/httpSuccess/inArray/isFunction/isReady/lastModified/makeArray/map/merge/multiFilter/noConflict/nth/param/parents/parse/post/prop/queue/ready/readyList/safariTimer/sibling/speed/swap/token/trim',
        'jQuery.fn':'_toggle/add/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/animate/append/appendTo/attr/before/bind/blur/change/children/click/clone/contains/css/dblclick/domManip/each/empty/end/eq/error/evalScripts/extend/fadeIn/fadeOut/fadeTo/filter/find/focus/get/gt/height/hide/hover/html/index/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/length/load/loadIfModified/lt/mousedown/mousemove/mouseout/mouseover/mouseup/next/not/one/parent/parents/prepend/prependTo/prev/pushStack/queue/ready/remove/removeAttr/removeClass/resize/scroll/select/serialize/setArray/show/siblings/size/slideDown/slideToggle/slideUp/submit/text/toggle/toggleClass/trigger/unbind/unload/val/width/wrap'
      },
      '1.2' : {
        "jQuery":"active/ajax/ajaxSettings/ajaxSetup/attr/boxModel/browser/cache/classFilter/className/clean/css/curCSS/data/dir/each/easing/event/expr/extend/filter/find/fn/fx/get/getJSON/getScript/globalEval/grep/handleError/httpData/httpNotModified/httpSuccess/inArray/isFunction/isReady/isXMLDoc/lastModified/makeArray/map/merge/multiFilter/noConflict/nodeName/nth/param/parse/post/prop/props/ready/readyList/removeData/sibling/speed/styleFloat/swap/timers/trim/unique",
        "jQuery.fn":"_toggle/add/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/click/clone/contents/css/dblclick/dequeue/domManip/each/empty/end/error/extend/fadeIn/fadeOut/fadeTo/filter/find/focus/get/hasClass/height/hide/hover/html/index/init/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/length/load/map/mousedown/mousemove/mouseout/mouseover/mouseup/next/nextAll/not/offset/one/parent/parents/prepend/prependTo/prev/prevAll/pushStack/queue/ready/remove/removeAttr/removeClass/replaceAll/replaceWith/resize/scroll/select/serialize/serializeArray/setArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/stop/submit/text/toggle/toggleClass/trigger/triggerHandler/unbind/unload/val/width/wrap/wrapAll/wrapInner"
      },
      '1.3' : {
        "jQuery":"Event/active/ajax/ajaxSettings/ajaxSetup/attr/boxModel/browser/cache/className/clean/css/curCSS/data/dequeue/dir/each/easing/event/expr/extend/filter/find/fn/fx/get/getJSON/getScript/globalEval/grep/handleError/httpData/httpNotModified/httpSuccess/inArray/isArray/isFunction/isReady/isXMLDoc/lastModified/makeArray/map/merge/multiFilter/noConflict/nodeName/nth/offset/param/post/prop/props/queue/ready/readyList/removeData/sibling/speed/support/swap/timerId/timers/trim/unique",
        "jQuery.fn":"_load/_toggle/add/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/click/clone/closest/contents/css/data/dblclick/dequeue/die/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/filter/find/focus/get/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/live/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/not/offset/offsetParent/one/outerHeight/outerWidth/parent/parents/position/prepend/prependTo/prev/prevAll/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/setArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/stop/submit/text/toggle/toggleClass/trigger/triggerHandler/unbind/unload/val/width/wrap/wrapAll/wrapInner"
      },
      '1.4' : {
        "jQuery":"Event/active/ajax/ajaxSettings/ajaxSetup/attr/attrFn/bindReady/boxModel/browser/cache/clean/contains/css/curCSS/data/dequeue/dir/each/easing/etag/event/expando/expr/extend/filter/find/fn/fragments/fx/get/getJSON/getScript/getText/globalEval/grep/guid/handleError/httpData/httpNotModified/httpSuccess/inArray/isArray/isEmptyObject/isFunction/isPlainObject/isReady/isXMLDoc/lastModified/makeArray/map/merge/noConflict/noData/nodeName/noop/nth/offset/param/post/props/proxy/queue/ready/removeData/sibling/speed/style/support/swap/timers/trim/uaMatch/unique",
        "jQuery.fn":"_load/_toggle/add/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/clearQueue/click/clone/closest/contents/css/data/dblclick/delay/dequeue/detach/die/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/filter/find/first/focus/focusin/focusout/get/has/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/last/length/live/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/nextUntil/not/offset/offsetParent/one/outerHeight/outerWidth/parent/parents/parentsUntil/position/prepend/prependTo/prev/prevAll/prevUntil/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/setArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/sort/splice/stop/submit/text/toArray/toggle/toggleClass/trigger/triggerHandler/unbind/unload/unwrap/val/width/wrap/wrapAll/wrapInner"
      },
      '1.5' : {
        "jQuery":"Deferred/Event/_Deferred/_data/acceptData/access/active/ajax/ajaxPrefilter/ajaxSettings/ajaxSetup/ajaxTransport/attr/attrFn/bindReady/boxModel/browser/buildFragment/cache/camelCase/clean/cleanData/clone/contains/css/cssHooks/cssNumber/cssProps/curCSS/data/dequeue/dir/each/easing/error/etag/event/expando/expr/extend/filter/find/fn/fragments/fx/get/getJSON/getScript/globalEval/grep/guid/hasData/inArray/isArray/isEmptyObject/isFunction/isNaN/isPlainObject/isReady/isWindow/isXMLDoc/lastModified/makeArray/map/merge/noConflict/noData/nodeName/noop/now/nth/offset/param/parseJSON/parseXML/post/props/proxy/queue/ready/readyWait/removeData/removeEvent/sibling/speed/style/sub/support/swap/text/timers/trim/type/uaMatch/unique/uuid/when",
        "jQuery.fn":"_toggle/add/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/clearQueue/click/clone/closest/constructor/contents/css/data/dblclick/delay/delegate/dequeue/detach/die/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/fadeToggle/filter/find/first/focus/focusin/focusout/get/has/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/last/length/live/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/nextUntil/not/offset/offsetParent/one/outerHeight/outerWidth/parent/parents/parentsUntil/position/prepend/prependTo/prev/prevAll/prevUntil/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/sort/splice/stop/submit/text/toArray/toggle/toggleClass/trigger/triggerHandler/unbind/undelegate/unload/unwrap/val/width/wrap/wrapAll/wrapInner"
      },
      '1.6' : {
        "jQuery":"Deferred/Event/_Deferred/_data/_mark/_unmark/acceptData/access/active/ajax/ajaxPrefilter/ajaxSettings/ajaxSetup/ajaxTransport/attr/attrFix/attrFn/attrHooks/bindReady/boxModel/browser/buildFragment/cache/camelCase/clean/cleanData/clone/contains/css/cssHooks/cssNumber/cssProps/curCSS/data/dequeue/dir/each/easing/error/etag/event/expando/expr/extend/filter/find/fn/fragments/fx/get/getJSON/getScript/globalEval/grep/guid/hasData/holdReady/inArray/isArray/isEmptyObject/isFunction/isNaN/isPlainObject/isReady/isWindow/isXMLDoc/lastModified/makeArray/map/merge/noConflict/noData/nodeName/noop/now/nth/offset/param/parseJSON/parseXML/post/prop/propFix/propHooks/proxy/queue/ready/readyWait/removeAttr/removeData/removeEvent/sibling/speed/style/sub/support/swap/text/timers/trim/type/uaMatch/unique/uuid/valHooks/when",
        "jQuery.fn":"_toggle/add/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/clearQueue/click/clone/closest/constructor/contents/css/data/dblclick/delay/delegate/dequeue/detach/die/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/fadeToggle/filter/find/first/focus/focusin/focusout/get/has/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/last/length/live/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/nextUntil/not/offset/offsetParent/one/outerHeight/outerWidth/parent/parents/parentsUntil/position/prepend/prependTo/prev/prevAll/prevUntil/promise/prop/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/removeProp/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/sort/splice/stop/submit/text/toArray/toggle/toggleClass/trigger/triggerHandler/unbind/undelegate/unload/unwrap/val/width/wrap/wrapAll/wrapInner"
      },
      '1.7' : {
        "jQuery":"Callbacks/Deferred/Event/_data/_mark/_unmark/acceptData/access/active/ajax/ajaxPrefilter/ajaxSettings/ajaxSetup/ajaxTransport/attr/attrFn/attrHooks/bindReady/boxModel/browser/buildFragment/cache/camelCase/clean/cleanData/clone/contains/css/cssHooks/cssNumber/cssProps/curCSS/data/dequeue/dir/each/easing/error/etag/event/expando/expr/extend/filter/find/fn/fragments/fx/get/getJSON/getScript/globalEval/grep/guid/hasData/holdReady/inArray/isArray/isEmptyObject/isFunction/isNumeric/isPlainObject/isReady/isWindow/isXMLDoc/lastModified/makeArray/map/merge/noConflict/noData/nodeName/noop/now/nth/offset/param/parseJSON/parseXML/post/prop/propFix/propHooks/proxy/queue/ready/readyWait/removeAttr/removeData/removeEvent/sibling/speed/style/sub/support/swap/text/timers/trim/type/uaMatch/unique/uuid/valHooks/when",
        "jQuery.fn":"_toggle/add/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/clearQueue/click/clone/closest/constructor/contents/contextmenu/css/data/dblclick/delay/delegate/dequeue/detach/die/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/fadeToggle/filter/find/first/focus/focusin/focusout/get/has/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/last/length/live/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/nextUntil/not/off/offset/offsetParent/on/one/outerHeight/outerWidth/parent/parents/parentsUntil/position/prepend/prependTo/prev/prevAll/prevUntil/promise/prop/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/removeProp/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/sort/splice/stop/submit/text/toArray/toggle/toggleClass/trigger/triggerHandler/unbind/undelegate/unload/unwrap/val/width/wrap/wrapAll/wrapInner"
      },
      '1.8' : {
        "jQuery":"Animation/Callbacks/Deferred/Event/Tween/_data/_queueHooks/acceptData/access/active/ajax/ajaxPrefilter/ajaxSettings/ajaxSetup/ajaxTransport/attr/attrFn/attrHooks/browser/buildFragment/cache/camelCase/clean/cleanData/clone/contains/css/cssHooks/cssNumber/cssProps/data/deletedIds/dequeue/dir/each/easing/error/etag/event/expando/expr/extend/filter/find/fn/fragments/fx/get/getJSON/getScript/globalEval/grep/guid/hasData/holdReady/inArray/isArray/isEmptyObject/isFunction/isNumeric/isPlainObject/isReady/isWindow/isXMLDoc/lastModified/makeArray/map/merge/noConflict/noData/nodeName/noop/now/offset/param/parseHTML/parseJSON/parseXML/post/prop/propFix/propHooks/proxy/queue/ready/readyWait/removeAttr/removeData/removeEvent/sibling/speed/style/sub/support/swap/text/timers/trim/type/uaMatch/unique/uuid/valHooks/when",
        "jQuery.fn":"add/addBack/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/clearQueue/click/clone/closest/constructor/contents/contextmenu/css/data/dblclick/delay/delegate/dequeue/detach/die/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/fadeToggle/filter/find/first/focus/focusin/focusout/get/has/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/last/length/live/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/nextUntil/not/off/offset/offsetParent/on/one/outerHeight/outerWidth/parent/parents/parentsUntil/position/prepend/prependTo/prev/prevAll/prevUntil/promise/prop/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/removeProp/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/sort/splice/stop/submit/text/toArray/toggle/toggleClass/trigger/triggerHandler/unbind/undelegate/unload/unwrap/val/width/wrap/wrapAll/wrapInner"
      },
      '1.9': {
        "jQuery":"Animation/Callbacks/Deferred/Event/Tween/_data/_queueHooks/_removeData/acceptData/access/active/ajax/ajaxPrefilter/ajaxSettings/ajaxSetup/ajaxTransport/attr/attrHooks/buildFragment/cache/camelCase/cleanData/clone/contains/css/cssHooks/cssNumber/cssProps/data/dequeue/dir/each/easing/error/etag/event/expando/expr/extend/filter/find/fn/fx/get/getJSON/getScript/globalEval/grep/guid/hasData/holdReady/inArray/isArray/isEmptyObject/isFunction/isNumeric/isPlainObject/isReady/isWindow/isXMLDoc/lastModified/makeArray/map/merge/noConflict/noData/nodeName/noop/now/offset/param/parseHTML/parseJSON/parseXML/post/prop/propFix/propHooks/proxy/queue/ready/readyWait/removeAttr/removeData/removeEvent/sibling/speed/style/support/swap/text/timers/trim/type/unique/valHooks/when",
        "jQuery.fn":"add/addBack/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/clearQueue/click/clone/closest/constructor/contents/contextmenu/css/data/dblclick/delay/delegate/dequeue/detach/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/fadeToggle/filter/find/finish/first/focus/focusin/focusout/get/has/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/last/length/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/nextUntil/not/off/offset/offsetParent/on/one/outerHeight/outerWidth/parent/parents/parentsUntil/position/prepend/prependTo/prev/prevAll/prevUntil/promise/prop/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/removeProp/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/sort/splice/stop/submit/text/toArray/toggle/toggleClass/trigger/triggerHandler/unbind/undelegate/unload/unwrap/val/width/wrap/wrapAll/wrapInner"
      },
      '1.10' : {
        "jQuery":"Animation/Callbacks/Deferred/Event/Tween/_data/_evalUrl/_queueHooks/_removeData/acceptData/access/active/ajax/ajaxPrefilter/ajaxSettings/ajaxSetup/ajaxTransport/attr/attrHooks/buildFragment/cache/camelCase/cleanData/clone/contains/css/cssHooks/cssNumber/cssProps/data/dequeue/dir/each/easing/error/etag/event/expando/expr/extend/filter/find/fn/fx/get/getJSON/getScript/globalEval/grep/guid/hasData/holdReady/inArray/isArray/isEmptyObject/isFunction/isNumeric/isPlainObject/isReady/isWindow/isXMLDoc/lastModified/makeArray/map/merge/noConflict/noData/nodeName/noop/now/offset/param/parseHTML/parseJSON/parseXML/post/prop/propFix/propHooks/proxy/queue/ready/readyWait/removeAttr/removeData/removeEvent/sibling/speed/style/support/swap/text/timers/trim/type/unique/valHooks/when",
        "jQuery.fn":"add/addBack/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/clearQueue/click/clone/closest/constructor/contents/contextmenu/css/data/dblclick/delay/delegate/dequeue/detach/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/fadeToggle/filter/find/finish/first/focus/focusin/focusout/get/has/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/last/length/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/nextUntil/not/off/offset/offsetParent/on/one/outerHeight/outerWidth/parent/parents/parentsUntil/position/prepend/prependTo/prev/prevAll/prevUntil/promise/prop/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/removeProp/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/sort/splice/stop/submit/text/toArray/toggle/toggleClass/trigger/triggerHandler/unbind/undelegate/unload/unwrap/val/width/wrap/wrapAll/wrapInner"
      },
      '1.11' : {
        "jQuery":"Animation/Callbacks/Deferred/Event/Tween/_data/_evalUrl/_queueHooks/_removeData/acceptData/access/active/ajax/ajaxPrefilter/ajaxSettings/ajaxSetup/ajaxTransport/attr/attrHooks/buildFragment/cache/camelCase/cleanData/clone/contains/css/cssHooks/cssNumber/cssProps/data/dequeue/dir/each/easing/error/etag/event/expando/expr/extend/filter/find/fn/fx/get/getJSON/getScript/globalEval/grep/guid/hasData/holdReady/inArray/isArray/isEmptyObject/isFunction/isNumeric/isPlainObject/isReady/isWindow/isXMLDoc/lastModified/makeArray/map/merge/noConflict/noData/nodeName/noop/now/offset/param/parseHTML/parseJSON/parseXML/post/prop/propFix/propHooks/proxy/queue/ready/readyWait/removeAttr/removeData/removeEvent/sibling/speed/style/support/swap/text/timers/trim/type/unique/valHooks/when",
        "jQuery.fn":"add/addBack/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/clearQueue/click/clone/closest/constructor/contents/contextmenu/css/data/dblclick/delay/delegate/dequeue/detach/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/fadeToggle/filter/find/finish/first/focus/focusin/focusout/get/has/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/last/length/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/nextUntil/not/off/offset/offsetParent/on/one/outerHeight/outerWidth/parent/parents/parentsUntil/position/prepend/prependTo/prev/prevAll/prevUntil/promise/prop/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/removeProp/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/sort/splice/stop/submit/text/toArray/toggle/toggleClass/trigger/triggerHandler/unbind/undelegate/unload/unwrap/val/width/wrap/wrapAll/wrapInner"
      },
      '2.0' : {
        "jQuery":"Animation/Callbacks/Deferred/Event/Tween/_data/_evalUrl/_queueHooks/_removeData/acceptData/access/active/ajax/ajaxPrefilter/ajaxSettings/ajaxSetup/ajaxTransport/attr/attrHooks/buildFragment/camelCase/cleanData/clone/contains/css/cssHooks/cssNumber/cssProps/data/dequeue/dir/each/easing/error/etag/event/expando/expr/extend/filter/find/fn/fx/get/getJSON/getScript/globalEval/grep/guid/hasData/holdReady/inArray/isArray/isEmptyObject/isFunction/isNumeric/isPlainObject/isReady/isWindow/isXMLDoc/lastModified/makeArray/map/merge/noConflict/nodeName/noop/now/offset/param/parseHTML/parseJSON/parseXML/post/prop/propFix/propHooks/proxy/queue/ready/readyWait/removeAttr/removeData/removeEvent/sibling/speed/style/support/swap/text/timers/trim/type/unique/valHooks/when",
        "jQuery.fn":"add/addBack/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/clearQueue/click/clone/closest/constructor/contents/contextmenu/css/data/dblclick/delay/delegate/dequeue/detach/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/fadeToggle/filter/find/finish/first/focus/focusin/focusout/get/has/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/last/length/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/nextUntil/not/off/offset/offsetParent/on/one/outerHeight/outerWidth/parent/parents/parentsUntil/position/prepend/prependTo/prev/prevAll/prevUntil/promise/prop/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/removeProp/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/sort/splice/stop/submit/text/toArray/toggle/toggleClass/trigger/triggerHandler/unbind/undelegate/unload/unwrap/val/width/wrap/wrapAll/wrapInner"
      },
      '2.1' : {
        "jQuery":"Animation/Callbacks/Deferred/Event/Tween/_data/_evalUrl/_queueHooks/_removeData/acceptData/access/active/ajax/ajaxPrefilter/ajaxSettings/ajaxSetup/ajaxTransport/attr/attrHooks/buildFragment/camelCase/cleanData/clone/contains/css/cssHooks/cssNumber/cssProps/data/dequeue/dir/each/easing/error/etag/event/expando/expr/extend/filter/find/fn/fx/get/getJSON/getScript/globalEval/grep/guid/hasData/holdReady/inArray/isArray/isEmptyObject/isFunction/isNumeric/isPlainObject/isReady/isWindow/isXMLDoc/lastModified/makeArray/map/merge/noConflict/nodeName/noop/now/offset/param/parseHTML/parseJSON/parseXML/post/prop/propFix/propHooks/proxy/queue/ready/readyWait/removeAttr/removeData/removeEvent/sibling/speed/style/support/swap/text/timers/trim/type/unique/valHooks/when",
        "jQuery.fn":"add/addBack/addClass/after/ajaxComplete/ajaxError/ajaxSend/ajaxStart/ajaxStop/ajaxSuccess/andSelf/animate/append/appendTo/attr/before/bind/blur/change/children/clearQueue/click/clone/closest/constructor/contents/contextmenu/css/data/dblclick/delay/delegate/dequeue/detach/domManip/each/empty/end/eq/error/extend/fadeIn/fadeOut/fadeTo/fadeToggle/filter/find/finish/first/focus/focusin/focusout/get/has/hasClass/height/hide/hover/html/index/init/innerHeight/innerWidth/insertAfter/insertBefore/is/jquery/keydown/keypress/keyup/last/length/load/map/mousedown/mouseenter/mouseleave/mousemove/mouseout/mouseover/mouseup/next/nextAll/nextUntil/not/off/offset/offsetParent/on/one/outerHeight/outerWidth/parent/parents/parentsUntil/position/prepend/prependTo/prev/prevAll/prevUntil/promise/prop/push/pushStack/queue/ready/remove/removeAttr/removeClass/removeData/removeProp/replaceAll/replaceWith/resize/scroll/scrollLeft/scrollTop/select/selector/serialize/serializeArray/show/siblings/size/slice/slideDown/slideToggle/slideUp/sort/splice/stop/submit/text/toArray/toggle/toggleClass/trigger/triggerHandler/unbind/undelegate/unload/unwrap/val/width/wrap/wrapAll/wrapInner"
      }
    };
    var ret = ons.split(',').filter(function (on) {
      return on !== '';
    }).map(function (on) {
      var o = window,
        ns = on.split(/\./g);
      for (var i = 0, n; n = ns[i]; ++i) {
        o = o[n];
        if (o === undefined) {
          return {};
        }
      }
      var keys = Object.keys(o).sort();
      var jqv = window.jQuery.fn.jquery.split('.', 2).join('.').replace(/[a-z]+[0-9]*/g,'');
      if ( jqv === "$R: 509 $"){
        jqv = '1.0';
      }
      if ( jqv === '@VERSION' ) {
        jqv = '1.8';
      }
      var dict = jqkeys[jqv][on].split('/');
      var added = keys.filter(function(k){ return dict.indexOf(k) === -1; } );
      var deled = dict.filter(function(k) { return keys.indexOf(k) === -1; } );
      return { '0': on, deled: deled, added: added };
    });
    return ret;
  }, objName);
  console.log(JSON.stringify(res));
  phantom.exit();
});
